NAME: VQVAE_HumanML3D_Local_Body_Hand_Sep_Trans_Final # Experiment names
ACCELERATOR: 'gpu' # Devices optioncal: “cpu”, “gpu”, “tpu”, “ipu”, “hpu”, “mps, “auto”
NUM_NODES: 1 # Number of GPU nodes for distributed training
DEVICE: [0, ] # Index of gpus eg. [0] or [0,1,2,3]
DEBUG: False
EXPER:
  motion_part: "body_hand_sep" # "body", "body_hand_sep", "body_hand_bind"
  motion_repre: "local cont6d" # "ske", "global cont6d", "local cont6d"
  transform: True # 
  token_interleaved: True #
  token_transform: True #
  framerate: 30
  max_length: 256

TRAIN:
  #---------------------------------
  STAGE: vae # stage "vae" , "lm_pretrain", "lm_instruct"
  #---------------------------------
  NUM_WORKERS: 12 # Number of workeqrs
  BATCH_SIZE: 96 # Size of batches
  END_EPOCH: 3001 # End epoch
  RESUME: '' # Resume training from this path
  PRETRAINED: 'SOLAMI/models/motiongpt/experiments/mgpt/VQVAE_HumanML3D_Local_Body_Hand_Sep_Trans_Final/checkpoints/epoch=2999.ckpt'
  PRETRAINED_VAE: 'SOLAMI/models/motiongpt/experiments/mgpt/VQVAE_HumanML3D_Local_Body_Hand_Sep_Trans_Final/checkpoints/epoch=2999.ckpt'

  OPTIM:
    target: AdamW
    params:
      lr: 1e-4
      betas: [0.9, 0.99]
      weight_decay: 0.0

# Evaluating Configuration
EVAL:
  BATCH_SIZE: 64 # Evaluating Batch size
  SPLIT: test

TEST:
  CHECKPOINTS: SOLAMI/models/motiongpt/experiments/mgpt/VQVAE_HumanML3D_Local_Body_Hand_Sep_Trans_Final/checkpoints/epoch=2999.ckpt
  SPLIT: test
  BATCH_SIZE: 32 # training Batch size
  SAVE_PREDICTIONS: False

DATASET:
  target: mGPT.data.HumanML3D.HumanML3DDataModule

METRIC:
  TYPE: ['MTMetrics']

LOSS:
  LAMBDA_FEATURE: 1.0
  LAMBDA_VELOCITY: 2.0
  LAMBDA_COMMIT: 0.1
  LAMBDA_CLS: 1.0
  ABLATION:
    RECONS_LOSS: 'l1_smooth'

model:
  target: mGPT.models.mgpt.MotionGPT
  params:
    condition: 'text'
    task: 't2m'
    lm: ${lm.gpt2_medium}
    motion_vae: ${vq.default}

LOGGER:
  TYPE: ['tensorboard'] #['tensorboard', 'wandb']
  VAL_EVERY_STEPS: 40
  WANDB:
    params:
      project: motiongpt